remote_theme: "jekyll/minima@c6e74bb"
google_analytics: UA-NNNNNNNN-N // Google Analyticsの有効化のために仮の値を設定
author: コシヒカリ
description: >
  ご連絡はX（旧Twitter）のDMまでお願いいたします。
lang: ja
twitter:
  username: jekyllrb
  card: summary_large_image